playframework/play1

framework/src/play/data/validation/Validation.java
framework/test-src/play/data/validation/ValidationTest.java

[lighthouse #1861](http://play.lighthouseapp.com/projects/57987/tickets/1861-validation-error-manipulation)

[#1861] feat(validation): add new methods insert, remove, hasError

---

framework/src/play/db/jpa/JPAPlugin.java

Remove useless onConfigurationRead function. It didn't do anything meaningful, nor was it used anywhere

[#1909] Update JPAPlugin.java

---

framework/src/play/data/validation/PhoneCheck.java
framework/test-src/play/data/validation/PhoneTest.java

* [#1903] test(phoneValidation): Add some test cases
[Lighthouse issue  #1903](http://play.lighthouseapp.com/projects/57987/tickets/1903-phone-validation-fails-in-some-cases)

* [#1903] fix(phoneValidation): fix validation to allow one number in the optional sub-zone

---

samples-and-tests/forum/app/views/Forums/show.html

[lighthouse #169](http://play.lighthouseapp.com/projects/57987-play-framework/tickets/169)

[#169] fix(forum): shows the last poster oh the thread

---

framework/src/play/templates/FastTags.java
framework/test-src/play/templates/JavaExtensionsTest.java
samples-and-tests/just-test-cases/app/controllers/tagDemos/TagDemos.java
samples-and-tests/just-test-cases/app/views/tagDemos/TagDemos/yesNo.html
samples-and-tests/just-test-cases/conf/routes

[lighthouse #1148](http://play.lighthouseapp.com/projects/57987/tickets/1148-yesno-evaluates-nullobject-as-true)

[#1148] fix(tag): yesno should  evaluates NullObject as false

---

framework/src/play/Invoker.java
framework/src/play/jobs/Job.java

[lighthouse #1908](http://play.lighthouseapp.com/projects/57987-play-framework/tickets/1908)

[#1908] fix(job): @OnApplicationStart fails if no plugin with filter found (ex JPAPlugin  disabled)

---

framework/src/play/libs/OAuth2.java
framework/src/play/libs/WS.java

[lighthouseapp 1344](http://play.lighthouseapp.com/projects/57987/tickets/1344-oauth2-lib-not-finding-access_token-inside-json-response)
Blocked google oauth2
Tested on 1.2.5.x-security.

[#1344] Fixed OAuth2 lib not finding access_token inside JSON response

---

framework/src/play/server/FileService.java

[lighthouse #1911](https://play.lighthouseapp.com/projects/57987/tickets/1911-play-throw-exception-in-ssl-mode)

[#1911] fix(FileService): check if channel is opened before using it

---

framework/templates/tags/script.tag
framework/templates/tags/stylesheet.tag

[lighthouse #1932](https://play.lighthouseapp.com/projects/57987-play-framework/tickets/1932-add-optional-parameter-in-script-stylesheet-tags-to-define-a-custom-path)

[#1932] feat(tag):Add optional parameter in script / stylesheet tags to define a custom path

---

framework/src/play/db/DB.java
framework/src/play/db/helper/JpaHelper.java
framework/src/play/db/jpa/JPA.java
framework/src/play/db/jpa/JPAModelLoader.java
framework/src/play/db/jpa/JPAPlugin.java
framework/src/play/test/Fixtures.java
samples-and-tests/multi-db/app/controllers/Application.java
samples-and-tests/multi-db/app/jobs/SomeJob.java
samples-and-tests/multi-db/app/utils/Gravatar.java

** fix some  leaks database connections when configured for multiple databases
* refactor(JPAModelLoader): move JPAModelLoader class in its own file
[Lighthouse #1933](https://play.lighthouseapp.com/projects/57987-play-framework/tickets/1933-play-130-leaks-database-connections-when-configured-for-multiple-databases#ticket-1933-2)

 [#1933] fix(multidb): fix some methods to call the correct db

---

framework/src/play/db/jpa/JPAPlugin.java

If any of the databases want the logging to be on, don't let the others turn it off again.

[#1923] Respect debugSQL of other configs

---

framework/src/log4j.properties
framework/src/play/Logger.java
framework/src/play/db/DBPlugin.java

[lighthouse #1924](https://play.lighthouseapp.com/projects/57987-play-framework/tickets/1924)

[#1924] fix(log): Sane c3p0 logging to use log4j or juli

---

.travis.yml
framework/src/play/db/DBPlugin.java
framework/src/play/libs/XML.java
framework/src/play/mvc/Router.java
framework/src/play/templates/FastTags.java
samples-and-tests/just-test-cases/app/controllers/Users.java
samples-and-tests/just-test-cases/app/controllers/security/XssAttempts.java
samples-and-tests/just-test-cases/app/views/Users/showAll.html
samples-and-tests/just-test-cases/app/views/security/XssAttempts/testUrlParam.html
samples-and-tests/just-test-cases/conf/routes
samples-and-tests/just-test-cases/test/security/XssAttempts/xssAttempts.test.html
samples-and-tests/just-test-cases/test/xssurltest.test.html

[lighthouseapp #1937](https://play.lighthouseapp.com/projects/57987-play-framework/tickets/1937-handle-diacritics-fro-keys-back-into-jsaction)

[#1937] fix(router): make some improvement in router 

---

framework/pym/play/commands/netbeans.py

Someone has been mixing tabs and spaces in here...

Fix indentation

---

documentation/commands/cmd-install.txt
framework/pym/play/commands/modulesrepo.py

[Lighthouse #1713](https://play.lighthouseapp.com/projects/57987/tickets/1713)

[#1713] force server param

---

resources/application-build.xml

…l play.ant.PlayConfigurationLoadTask

[#1917] fix(ant): add "play libs" path to classpath to be able to call play.ant.PlayConfigurationLoadTask

---

framework/src/play/templates/FastTags.java
samples-and-tests/just-test-cases/app/views/Users/showAll.html
samples-and-tests/just-test-cases/test/templates/fasttags/jsAction.test.html
samples-and-tests/just-test-cases/test/templates/fasttags/jsAction.yml

[Lighthouse #1574](https://play.lighthouseapp.com/projects/57987/tickets/1574-125-jsaction-problem-with-zero-and-false-values)

[#1574] fix(jsAction): Fix problem with zero and false values

---

framework/pym/play/commands/autotest.py

[Lighthouse #1960](https://play.lighthouseapp.com/projects/57987-play-framework/tickets/1960-problem-to-run-specific-tests-selenium)

 [#1960] fix(test): Fix running specific tests selenium

---

framework/src/play/data/FileUpload.java
framework/src/play/data/binding/types/FileBinder.java
framework/src/play/data/binding/types/UploadBinder.java
samples-and-tests/just-test-cases/app/controllers/Binary.java
samples-and-tests/just-test-cases/test/BinaryTest.java

[Lighthouse #1564](https://play.lighthouseapp.com/projects/57987/tickets/1564-cant-upload-a-file-whose-filesize-is-0b)

[#1564] fix(upload): allow upload zero size file

---

framework/src/play/libs/OpenID.java

[Lighthouse #1961](https://play.lighthouseapp.com/projects/57987/tickets/1961-openid-discovery-fails-in-13x-in-some-cases)

[#1961] Fixes OpenID discovery issue.

---

documentation/manual/deployment.textile

Remove section about playpps.net. It does no longer exist.

[#1968] Update deployment.textile : Remove section about playapps.net

---

resources/application-skel/conf/application.conf

FIx #1963  typo in application.conf

Fix #1963 typo in application.conf

---

framework/src/play/mvc/Router.java

[lighthouse 1972](https://play.lighthouseapp.com/projects/57987/tickets/1972)

* [#1972] fix(Router): Fix reverse routing of spaces to path not working because it doesn't replace "+" with "%20"

---

framework/src/play/data/parsing/ApacheMultipartParser.java
framework/src/play/data/parsing/DataParser.java
framework/src/play/data/parsing/DataParsers.java
framework/src/play/mvc/Scope.java
framework/test-src/play/data/binding/DataParsersTest.java

Original problem description: https://play.lighthouseapp.com/projects/57987-play-framework/tickets/1962-getting-static-initialization-deadlock-in-class-dataparser

Fix deadlock in data parser

---

framework/src/play/mvc/Router.java

Improve performance of method Router.reverse() by caching previous findings.
Ticket: https://play.lighthouseapp.com/projects/57987-play-framework/tickets/1980-improve-performance-of-routerreverse

Speedup router

---

framework/src/play/libs/WS.java
framework/src/play/libs/ws/WSAsync.java
framework/src/play/libs/ws/WSUrlFetch.java
samples-and-tests/just-test-cases/test/WSTest.java

[Lighthouse #1991](https://play.lighthouseapp.com/projects/57987-play-framework/tickets/1991-add-ability-to-manually-set-the-virtualhost-of-ws)

[#1991] feat(WS): Add ability to manually set a VirtualHost

---

documentation/commands/cmd-auto-test.txt
documentation/manual/configuration.textile
framework/pym/play/commands/autotest.py
modules/testrunner/src/play/modules/testrunner/FirePhoque.java

…Runner module
* doc(headlessBrowser): update available version for headlessBrowser
[Lighthouse #1958](https://play.lighthouseapp.com/projects/57987/tickets/1958-add-ability-to-define-the-timeout-in-testrunner-module)

* [#1958] feat(testRunner): Add ability to define the timeout

---

framework/src/play/PlayPlugin.java
framework/src/play/cache/Cache.java
framework/src/play/data/binding/Unbinder.java
framework/src/play/data/parsing/ApacheMultipartParser.java
framework/src/play/data/parsing/DataParser.java
framework/src/play/data/parsing/MultipartStream.java
framework/src/play/db/jpa/GenericModel.java
framework/src/play/db/jpa/JPABase.java
framework/src/play/db/jpa/JPAPlugin.java
framework/src/play/i18n/Messages.java
framework/src/play/libs/CronExpression.java
framework/src/play/libs/Crypto.java
framework/src/play/libs/Files.java
framework/src/play/libs/Mail.java
framework/src/play/libs/MimeTypes.java
framework/src/play/libs/WS.java
framework/src/play/libs/mail/test/LegacyMockMailSystem.java
framework/src/play/libs/ws/WSAsync.java
framework/src/play/mvc/Controller.java
framework/src/play/mvc/Http.java
framework/src/play/mvc/Mailer.java
framework/src/play/mvc/Router.java
framework/src/play/mvc/results/Redirect.java

[#1997] Fix javadoc tools errors

---

documentation/manual/configuration.textile
framework/src/play/server/PlayHandler.java
framework/src/play/server/ssl/SslHttpServerPipelineFactory.java

[lighthouse #2004](https://play.lighthouseapp.com/projects/57987-play-framework/tickets/2004-add-ability-to-define-enabled-ssl-protocols)

[#2004]  feat(ssl): Add ability to define enabled protocols

---

framework/src/play/libs/WS.java
framework/src/play/libs/ws/WSAsync.java
framework/src/play/libs/ws/WSUrlFetch.java
framework/src/play/mvc/Router.java

* [#1988] Add PATCH request support to Router

[#1988] Add PATCH request support to WS.WSRequest

---

framework/test-src/play/PlayBuilder.java
framework/test-src/play/libs/ImagesTest.java

[Lighthouse #1993](https://play.lighthouseapp.com/projects/57987/tickets/1993-imagestestjava-test-fails-when-running-ant-unittest)

* [#1993] test(images): fix path to run test with ant task

---

framework/dependencies.yml

[Lighthouse #1939](https://play.lighthouseapp.com/projects/57987/tickets/1939-update-to-groovy-24x)

 [#1939] chore(lib): Update to groovy from 2.3.9 to 2.4.5

---

samples-and-tests/just-test-cases/app/controllers/security/Security.java
samples-and-tests/just-test-cases/app/views/security/Security/login.html
samples-and-tests/just-test-cases/conf/dependencies.yml
samples-and-tests/just-test-cases/conf/routes
samples-and-tests/just-test-cases/test/secure/login.test.html

[PlayLighthouse #2014](https://play.lighthouseapp.com/projects/57987-play-framework/tickets/2014-message-not-appear-corretly-in-secure-module)

[#2014] fix(secure): Fix problem in secure module avoid to flash incorrect content

---

framework/src/play/db/jpa/JPAPlugin.java

The PR #767 tried to fix classloading issues w/ Hibernate, but using a precompiled app, this fix sill fails for a custom a NamingStrategy (and maybe other configs as well).
In the "precompile" step, Play sets the global classloader, so we do this (temporarily) for the JPA configuration as well.

[#2007] Fix JPA classloader issues by hooking up Play's classloader

---

framework/src/play/classloading/ApplicationCompiler.java
framework/src/play/classloading/BytecodeCache.java
framework/src/play/classloading/enhancers/LocalvariablesNamesEnhancer.java
framework/src/play/classloading/hash/ClassStateHashCreator.java
framework/src/play/data/validation/UniqueCheck.java
framework/src/play/db/Evolutions.java
framework/src/play/libs/CronExpression.java
framework/src/play/libs/Images.java
framework/src/play/libs/Mail.java
framework/src/play/libs/mail/test/LegacyMockMailSystem.java
framework/src/play/mvc/results/Redirect.java
framework/src/play/templates/JavaExtensions.java
framework/src/play/utils/HTML.java
framework/src/play/utils/Utils.java

Use StringBuilder as a small performance boost and best-practice where possible (as a thread-safe/synchronized access is not needed).

[#2017] Use StringBuilder instead of StringBuffer

---

.travis.yml
samples-and-tests/just-test-cases/test/WSTest.java

fix(travis): move back to the old infrastructure

---

framework/src/play/classloading/enhancers/LocalvariablesNamesEnhancer.java
framework/src/play/classloading/enhancers/SigEnhancer.java
framework/src/play/data/validation/UniqueCheck.java
framework/src/play/templates/JavaExtensions.java
framework/src/play/vfs/VirtualFile.java

Lighthouse ticket: https://play.lighthouseapp.com/projects/57987-play-framework/tickets/2021-optimize-usage-of-stringbuilder

optimize usage of StringBuilder

---

framework/src/play/i18n/Lang.java

Cache result of method Lang.getLocale()
this method can be called many times on every page, and it iterates all 150+ available locales.
Lighthouse ticket: https://play.lighthouseapp.com/projects/57987-play-framework/tickets/2027-cache-method-langgetlocale

[#2027] Cache locale

---

framework/src/play/classloading/ApplicationClassloader.java
framework/src/play/templates/GroovyTemplateCompiler.java
framework/src/play/test/TestEngine.java

Ticket: https://play.lighthouseapp.com/projects/57987/tickets/2040-concurrentmodificationexception-in-groovytemplatecompilerendtag

Fix fast tags assignable classes

---

framework/src/play/inject/Injector.java

…which Play classloader returns
@xael-fry  this change is critical to fix Play Guice plugin after PR https://github.com/playframework/play1/pull/966
This is a second PR for the ticket https://play.lighthouseapp.com/projects/57987/tickets/2040-concurrentmodificationexception-in-groovytemplatecompilerendtag

make play.inject.Injector work with unmodifiable class lists

---

framework/src/play/db/Evolutions.java

[Lighthouse #2049](https://play.lighthouseapp.com/projects/57987-play-framework/tickets/2049)

* [#2049] fix(evolutions): Some resultsets are not close in Evolutions causing some leak

---

framework/src/play/mvc/Scope.java
framework/test-src/play/mvc/ScopeTest.java

https://play.lighthouseapp.com/projects/57987-play-framework/tickets/2052-sessionput-works-incorrectly-with-null-objects

[#2052] make session put with Object work the same way as with String

---

framework/src/play/i18n/Messages.java
framework/src/play/mvc/Scope.java
framework/test-src/play/mvc/ScopeTest.java

[#996] fix(messages): ensure default is null before using it

[#996] fix(flash): flash method should handle the value as a key message

---

framework/src/play/mvc/results/RenderTemplate.java

separately from controller execution time.

Calculate template rendering time, so it can be logged/profiled

---

framework/src/play/templates/GroovyTemplateCompiler.java

it revert modif on GroovyTemplateCompiler.java don in 765dec207a563d80069665d0df40cc32c6ffec6a

[#1009] fix(templates): not log error and exception when compilin a template with a non GroovyInlineTag

---

.travis.yml

* see https://github.com/travis-ci/travis-ci/issues/5227#issuecomment-165131913

[#1014] chore(trvais): fix buffer overflow exception

---

framework/src/play/ConfigurationChangeWatcherPlugin.java

[#1008] fix(ConfigurationChangeWatcherPlugin): initialized configLastModified on application start

---

framework/src/play/mvc/Router.java
samples-and-tests/just-test-cases/conf/routes
samples-and-tests/just-test-cases/test/routing.test.html

[#998] fix(router): allow to have space when defining static args in routes

---

framework/src/play/server/Server.java

This is useful for easier running of play.server.Server directly from an IDE.

Default application.path to working directory

---

documentation/manual/configuration.textile
framework/src/play/db/DBPlugin.java

Detect changed for JNDI datasource which using jndi: prefix and its documentation - 1.3.x

---

documentation/manual/configuration.textile
framework/src/play/db/DBPlugin.java

Detect changed for JNDI datasource which using jndi: prefix and its documentation - 1.2.x

---

documentation/manual/configuration.textile
framework/src/play/db/DBConfig.java

Detect changed for JNDI datasource which using jndi: prefix and its documentation

---

framework/src/play/mvc/ActionInvoker.java

```
public class SecurityCtl extends Controller {
@Util
@Before(priority = 0)
public static void checkAuth() {
//if user is authorized then ok
if (request.cookies.containsKey("AUTH_TOKEN")) {
final Cookie cookie1 = request.cookies.get("AUTH_TOKEN");
final String token = cookie1.value;
//if token exists in DB
} else {
throw new UnauthorizedException();
}
}
@Util
@Catch(priority = 0, value = Throwable.class)
protected static void handleExceptions(Throwable t) {
//if not web socket
if (response != null) {
response.status = 500;
Logger.error(t, "ERROR");
renderJSON(String.format("{\"errorCode\":%d, \"description\":\"%s\"}", response.status, t.getMessage()));
}
}
}
```
Controller class:
```
@With(SecurityCtl.class)
public class MyCtl extends Controller {
public static void getUser(Long id) { …
```

Catch exception that has been thrown in method annotated with @Before

---

framework/src/play/mvc/results/RenderJson.java

so we can catch them in unit-tests and verify al parameters

Add getters to render json

---

framework/src/play/mvc/ActionInvoker.java
framework/test-src/play/mvc/ActionInvokerTest.java

After merging the PR #963 there is a regression:
@Catch method now catches Results produced by @Before methods.
This pull request fixes this issue as well as makes the code of ActionInvoker simpler and much more readable.

Fix PR #963

---

framework/src/play/mvc/results/Error.java
framework/src/play/mvc/results/NotModified.java
framework/src/play/mvc/results/Redirect.java
framework/src/play/mvc/results/RedirectToStatic.java
framework/src/play/mvc/results/RenderBinary.java
framework/src/play/mvc/results/RenderHtml.java
framework/src/play/mvc/results/RenderJson.java
framework/src/play/mvc/results/RenderTemplate.java
framework/src/play/mvc/results/RenderText.java
framework/src/play/mvc/results/RenderXml.java
framework/src/play/mvc/results/Status.java
framework/src/play/mvc/results/Unauthorized.java

PR for issue https://github.com/playframework/play1/issues/1056

Add getters to results

---

framework/src/play/mvc/ActionInvoker.java
framework/test-src/play/mvc/ActionInvokerTest.java

PR for fixing issue https://github.com/playframework/play1/issues/1061

Do not catch results in catch method

---

framework/src/play/i18n/Messages.java

[#1064] fix(messages): add some test on parameters to avoid NullpointerException

---

framework/src/play/deps/DependenciesManager.java
framework/src/play/deps/SettingsParser.java

* [#1051] fix(DependenciesManager): display error when running dependencies

---

documentation/manual/configuration.textile
framework/src/play/templates/TemplateLoader.java
resources/application-skel/conf/application.conf

see https://play.lighthouseapp.com/projects/57987/tickets/2071

[#2071] precompile additional templates

---

samples-and-tests/just-test-cases/app/controllers/tagDemos/TagDemos.java
samples-and-tests/just-test-cases/app/views/tagDemos/TagDemos/set.html
samples-and-tests/just-test-cases/test/tagDemos/TagDemos/set.test.html

[#1067] test(tag): add demo and test for used of #{set} and #{get}

---

documentation/manual/home.textile
documentation/manual/releases/release1.4.x/releasenotes-1.4.4.textile

[#1089] documentation(release): add documentation for 1.4.4

---

.travis.yml
README.textile
documentation/manual/configuration.textile
documentation/manual/home.textile
documentation/manual/releases/releases.textile
documentation/manual_ja/configuration.textile
framework/build.xml
framework/pym/play/application.py
framework/pym/play/commands/eclipse.py
framework/src/play/classloading/ApplicationCompiler.java
resources/_nbproject/project.xml
resources/application-skel/conf/application.conf
resources/idea/imlTemplate.xml
resources/idea/iprTemplate.xml
samples-and-tests/chat/conf/application.conf
samples-and-tests/facebook-oauth2/conf/application.conf
samples-and-tests/java8Support/conf/application.conf
samples-and-tests/modules/testModule/build.xml
samples-and-tests/multi-db/conf/application.conf
samples-and-tests/twitter-oauth/conf/application.conf

[#1096] drop support java prior1.8

---

framework/src/play/CorePlugin.java
framework/src/play/classloading/ApplicationClasses.java
framework/src/play/classloading/ApplicationCompiler.java
framework/src/play/classloading/enhancers/LocalvariablesNamesEnhancer.java
framework/src/play/classloading/enhancers/LocalvariablesNamesEnhancerJava7.java
framework/src/play/utils/Java.java

[#1097] java8 parameters

---

framework/pym/play/commands/base.py
framework/src/play/Play.java
framework/src/play/deps/YamlParser.java
resources/application-skel/conf/dependencies.yml

now it can be added to any application in dependencies.yml - as any other module

Fixes #1103 do not include `docviewer` module by default

---

documentation/manual/asynchronous.textile
documentation/manual_ja/asynchronous.textile

Fixes #1111 fix documentation for WebSockets

---

framework/src/play/db/DBPlugin.java

add c3p0 connection status index for Display the running application's status

c3p0 connection status

---

documentation/commands/cmd-dependencies.txt
framework/pym/play/commands/deps.py
framework/src/play/deps/DependenciesManager.java
framework/test-src/play/deps/DependenciesManagerTest.java

it creates modules directories without version numbers
@xael-fry I personally am in doubt with parameter name:
```play deps --shortModuleNames```. 
Is it readable enough?

#1142 add parameter `--shortModuleNames` to `play deps` command

---

framework/src/play/plugins/PluginCollection.java
framework/test-src/play/plugins/PluginCollectionTest.java

See issue https://github.com/playframework/play1/issues/1162

search play.plugins descriptor in application path

---

.travis.yml

[lightouse #2131](https://play.lighthouseapp.com/projects/57987/tickets/2131)

[#2131] update travis for new worker

---

framework/build.xml

[Lighthouse #2123](https://play.lighthouseapp.com/projects/57987-play-framework/tickets/2123)

[#2123]Cannot run program "python": CreateProcess error=2

---

framework/build.xml

[Lighthouse #2126](https://play.lighthouseapp.com/projects/57987-play-framework/tickets/2126)

[#2126] MessagesTest.class testMessageInAnotherLanguage set explicit test language for just-test-cases

---

.travis.yml
framework/pym/play/commands/autotest.py
framework/test-src/play/templates/FastTagsTest.java
modules/testrunner/conf/logging.properties
modules/testrunner/src/play/modules/testrunner/FirePhoque.java

Fixes https://play.lighthouseapp.com/projects/57987-play-framework/tickets/2122

[#2122]FastTagsTest:ComparisonFailure:differences only in line separator

---

.travis.yml
framework/build.xml
framework/pym/play/commands/autotest.py
framework/src/play/Logger.java
framework/test-src/play/templates/FastTagsTest.java
modules/testrunner/conf/logging.properties
modules/testrunner/src/play/modules/testrunner/FirePhoque.java
python/Lib/unittest.py

fixes waitFor 'I am a debug message'
for details see https://play.lighthouseapp.com/projects/57987/tickets/2125-testloglevelsandlog4jconfig-timeout-waitfor-i-am-a-debug-message

[#2125]testLogLevelsAndLog4jConfig TIMEOUT

---

framework/pym/play/commands/status.py

As discussed, a fix to make the "play status" command work with the "new" secret key style

remove signing and use statusKey as a traditional secret key

---

framework/src/play/jobs/JobsPlugin.java

[#2154] Fixes NPE

---

framework/src/play/mvc/Http.java
framework/src/play/server/PlayHandler.java
framework/src/play/server/ServletWrapper.java
framework/src/play/utils/HTTP.java
framework/test-src/play/server/ServletWrapperTest.java
framework/test-src/play/utils/HTTPTest.java

Fix error logging - the Throwable argument was just ignored
Also, duplicated code was removed in related methods, added JUnit tests

[#2144] Fix error logging - the Throwable argument was just ignored

---

framework/src/play/mvc/Controller.java
framework/test-src/play/mvc/ControllerTest.java

* refactor(tests): issue #1200, adds Controller.test class and unit test for modification on this issue
* fix(tests): issue #1200, fixes missing imports
* fix(tests): issue #1200, fixes encapsulation
* fix(tests): issue #1200 sorted import errors
* style(tests): issue #1200 beautification
CF #1200 #1245

fix(tests): issue #1200, added testing compatibility for jdk9+

---

framework/src/play/libs/F.java
samples-and-tests/just-test-cases/test/Promises.java

This fixes a subtle race condition that caused a variety of pathological behavior on a Play applications, particularly when a controller action invokes a job that finishes quickly.
1) await(Future) "returns" twice (in two different threads)
2) After await(Future), some controller action parameters are null.
3) In await(Future), there's a ConcurrentModificationException
The change includes a new regression test for the race.

[#2086] Fix race in Promise.onRedeem() that called "callback" twice

---

documentation/manual/home.textile
documentation/manual/releases/release1.5.x/releasenotes-1.5.2.textile
documentation/manual/releases/releases.textile

Fixes #1270 
Has documentation for play 1.5.2
cf issue #1270

[#1270] doc(release): add documentation for play 1.5.2

---

documentation/manual/configuration.textile
framework/src/play/server/PlayHandler.java
framework/src/play/server/ServletWrapper.java

Fixes #1300 
The purpose of this PR is to allow user to define allowed methods that can be defined in 'X-HTTP-Method-Override'

[#1300] feat: Define allowed methods used in 'X-HTTP-Method-Override'

---

framework/test-src/play/plugins/PluginCollectionTest.java
framework/test-src/play/plugins/custom-play.duplicate.plugins
framework/test-src/play/plugins/custom-play.plugins.duplicate

[#2155] Silent or suppressed errors in unittest PluginCollectionTest#skipsDuplicatePlugins

---

README.textile

Fixes Document Url
remove error urls
no

update document url

---

framework/src/play/mvc/Scope.java

[#1316] Replace coma with comma

---

documentation/manual/home.textile
documentation/manual/releases/release1.6.x/releasenotes-1.6.0.textile
documentation/manual/releases/releases.textile

Prepare release 1.6.0

---

documentation/commands/cmd-status.txt

The docs were wrong, I had to look in the code on how to use it.
Fix it here for those who come after me.
Hopefully save them some time.

Fix docs for `play status`

---

.github/workflows/build-test.yml

The Play 2 team is migrating all its repositories within the Play Framework organization to GitHub actions in the next weeks.
Move to github actions,

#1371 add github-actions.yml

---

framework/src/play/db/Evolutions.java

Fixes #383
Add a fix to support disabled evolutions when using the command line evolutions operations.

[#1383] ♻ Support disabled evolutions for command line operations

---

documentation/manual/configuration.textile

Added an additional explanation for assigning a specific database within a model by using the PersistenceUnit annotation.

MultiDb: Additional documentation

---

framework/pym/play/commands/intellij.py

no initialization playHome
Fixes #1399
fixed "UnboundLocalError: local variable 'playHome' referenced before assignment"

fixed #1399 "UnboundLocalError: local variable 'playHome' referenced before assignment

---

framework/src/play/classloading/ApplicationClasses.java

#1405: replace HashMap be ConcurrentHashMap

---

framework/pym/play/application.py

Do not run application on unsupported jvm version. Unsupported versions according to [ApplicationCompiler](/playframework/play1/tree/master/framework/src/play/classloading/ApplicationCompiler.java#L70)

update check of java version

---

.github/workflows/build-test.yml

Fixes #1446
Remove python2 since it was removed on june 19
Are there any relevant issues / PRs / mailing lists discussions?

[#1146] test(python): use python 3 for build instead of deprecated python2

---

documentation/manual/home.textile
documentation/manual/releases/release1.8.x/releasenotes-1.8.0.textile
documentation/manual/releases/releases.textile

Update release notes for 1.8.0

documentation(release): update documentation for release 1.8.0

---

.github/release-drafts/increasing-minor-version.yml

fix(release-draft): fix version number

---

framework/src/play/classloading/ApplicationClassloader.java

Fixes #1496
Prevents ConcurrentModificationException

refs#1496 ConcurrentModificationException when resolved a new classname

---

framework/src/play/Play.java
framework/src/play/classloading/enhancers/ContinuationEnhancer.java
framework/src/play/data/binding/Unbinder.java
framework/src/play/data/binding/types/BinaryBinder.java
framework/src/play/db/DBPlugin.java
framework/src/play/db/jpa/JPAModelLoader.java
framework/src/play/db/jpa/JPQL.java
framework/src/play/libs/Mail.java
framework/src/play/libs/WS.java
framework/src/play/libs/XML.java
framework/src/play/mvc/ActionInvoker.java
framework/src/play/server/HttpServerPipelineFactory.java
framework/src/play/utils/Properties.java
framework/src/play/utils/Utils.java
framework/templates/tags/fixture.tag

Fixes deprecation with Class.newInstance()
Also fixes a deprecation with Runtime.exec().
[Are there any relevant issues / PRs / mailing lists discussions?](https://github.com/playframework/play1/pull/1439/)

Fix class newinstance deprecation
