playframework/play1

documentation/manual/configuration.textile
framework/src/play/classloading/ApplicationCompiler.java

** 1.5 no longer supported
** 1.8 experimental (cf hibernate)
* [#1904] feat(compiler): default compiler version of source = 1.6

[#1904] doc(configuration): update doc java.source

---

framework/pym/play/application.py
framework/pym/play/commands/base.py
framework/pym/play/commands/deps.py
framework/pym/play/commands/evolutions.py
framework/pym/play/utils.py

Moving `java_path()` out of application into utils so `getJavaVersion()` can use it too

[#1902] Use JAVA_HOME in getJavaVersion

---

framework/src/play/Invoker.java

I would prefer this solutions, because from a functional perspective it is essential that the play.Invoker.Invocation.execute() is called and not that a filter is found!

[#1908] fixes: @OnApplicationStart fails if you disable the JPAPlugin

---

framework/src/log4j.properties
framework/src/play/Logger.java
framework/src/play/db/DBPlugin.java

play1 simultaneously uses c3p0 as its default Connection pool but sends all c3p0 logging to `/dev/null` (metaphorically speaking). That renders applications which experience database problems very difficult to debug.
c3p0's logging is unreasonably verbose at DEBUG/FINE/TRACE levels, but is reasonably quiet at INFO and very quiet at WARN or above, unless something really breaks. The library is intended to be logged at INFO. But it does emit an full configuration dump on pool initialization at INFO.
Presumably someone got annoyed by c3p0's logging and (insanely) just swept it away all at once.
This pull request restores c3p0 logging at WARN level. From the perspective of a guy who often gets c3p0 support requests, I'd prefer logging at INFO, so users can view and report their pool …

[#1924] Sane c3p0 logging

---

documentation/commands/cmd-start.txt
framework/build.xml
framework/pym/play/application.py
play
samples-and-tests/i-am-a-developer/mock.py
samples-and-tests/i-am-a-developer/test_jvm_version_flag.py

```getJavaVersion()``` (introduced in 8f5e3e591baf50cbfda11722cd4195957c598d14) spawns a subprocess, which bumps the PID count, which breaks [Upstart](http://upstart.ubuntu.com/), the latter which expects Play to fork exactly none, once or twice, depending on which ```expect``` stanza you use.

[#1916] Get Java version from application.conf

---

framework/src/play/data/validation/IPv4AddressCheck.java
framework/test-src/play/data/validation/IpAddressTest.java
framework/test-src/play/data/validation/PhoneTest.java

* Add ipv4Address validation test
* fix typo in PhoneTest method
[Lighthouse #1892](https://play.lighthouseapp.com/projects/57987/tickets/1892-ipv4addresscheck-allows-invalid-addresses)

* [#1892] fix(IPv4AddressCheck): fix validation to avoid additional character(+, .)

---

framework/src/play/libs/Images.java

[Lighthouse #1230](https://play.lighthouseapp.com/projects/57987/tickets/1230-playlibsimagecrop-dont-close-the-outputstream)

[#1230] fix(image): Close the OutputStream in image.crop

---

framework/src/play/CorePlugin.java

MonitorFactory.getRootMonitor().getBasicData() now returns one additional column (Instance), breaking index-based column access.
This patch now uses proper Monitor.getXX methods instead of error-prone indices and thus restores monitor status functionality in play 1.3.2

[#1967] fix broken monitor statistics in status - make the code more future-proof as well

---

framework/src/play/data/binding/types/BinaryBinder.java

the fix for [#1564] breaks Blob binding, this fix resolves this by checking for an empty file name instead of a 0-size (which has resulted in a NPE)

fix: allow zero-length blobs

---

framework/src/play/data/FileUpload.java
framework/src/play/data/binding/types/FileArrayBinder.java
framework/test-src/play/data/FileUploadTest.java

We have a lot of optional "file upload" controls in our web application.
When submitting a form without any files uploaded, FileArrayBinder throws NullPointerException.

Fix NPE in FileArrayBinder if no files are uploaded

---

framework/src/play/plugins/PluginCollection.java

If a plugin with the same index and class name is specified multiple times, it is loaded only once.   This seems like a reasonable feature -- I can't think of a use case where loading the same plugin at the same priority multiple times would be desirable.
It also works around cases where Play.classloader.getResources("play.plugins") returns multiple copies of the plugin file.  https://play.lighthouseapp.com/projects/57987/tickets/176-app-playplugins-loaded-twice-conf-on-2-classpaths documents one case where this happened.    I've run into a similar issue occasionally with 1.3.1 on Win32 systems:   Play.classloader.getResources("play.plugins") will occasionally return ["/c:/app/path/conf/play.plugins", "/C:/app/path/conf/play.plugins"] and load everything twice.  I haven't been able to pin …

De-dupes list of plugins before load to avoid #176 and other issues.

---

documentation/manual/configuration.textile
framework/src/play/mvc/Http.java

[#lighthouse #1772](https://play.lighthouseapp.com/projects/57987-play-framework/tickets/1772)

[#1772] Fix redirect to wrong domain and port behind apache 

---

framework/src/play/jobs/Job.java
framework/src/play/jobs/JobsPlugin.java

…ionStart and @Every
* Previously these jobs would be displayed twice in application status.
* refactor(JobPlugin):Fixed some compiler warnings
* refactor(JobPlugin): Create executor and scheduledJobs at the same time to prevent unexpected NPEs during startup
* refactor(JobPlugin):Be consistent with how jobs are displayed in application status: use toString() in both 'Scheduled jobs' and 'Waiting jobs'
* refactor(JobPlugin):Make JobsPlugin aware of Jobs scheduled programmatically with Job.every() and display them in application status
* refactor(JobPlugin): Use Job.toString() also in monitor name, for consistency with Scheduled Jobs and Waiting Jobs
[Lighthouse #1983](https://play.lighthouseapp.com/projects/57987-play-framework/tickets/1983)

[#1983] Fix jobs plugin

---

framework/src/play/PlayPlugin.java
framework/src/play/mvc/ActionInvoker.java
framework/src/play/plugins/PluginCollection.java

We need a plugin method that is guaranteed to be called after **every** action (no matter if action execution succeeded or failed). Now Play1 doesn't have such a method.
Ticket: https://play.lighthouseapp.com/projects/57987-play-framework/tickets/2002-add-method-pluginonactioninvocationfinally

add method Plugin.onActionInvocationFinally

---

documentation/manual/configuration.textile
framework/src/play/db/DBPlugin.java

* add more configurable c3p0 properties (e.g. maxIdleTime)
* remove hardcoded settings acquireRetryAttempts=10, idleConnectionTestPeriod=10, testConnectionOnCheckin=true
Ticket: https://play.lighthouseapp.com/projects/57987-play-framework/tickets/1995-make-db-properties-configurable

[#1995] make DB properties configurable

---

framework/src/play/db/Configuration.java
framework/test-src/play/db/ConfigurationTest.java

In current Play implementation, putting property to custom DB configuration uses wrong property name.
See this failing test:
```java
@Test
public void putPropertyToCustomConfiguration() {
Configuration configuration = new Configuration("custom");
configuration.put("db.driver", "com.oracle.OracleDriver");
assertEquals("com.oracle.OracleDriver", configuration.getProperty("db.driver"));
}
```
This pull request makes this test green. 
See ticket https://play.lighthouseapp.com/projects/57987-play-framework/tickets/1992-fix-putting-property-to-customer-db-configuration

fix putting property to customer DB configuration

---

framework/src/play.plugins
framework/src/play/ConfigurationChangeWatcherPlugin.java
framework/src/play/Play.java
framework/test-src/play/plugins/PluginCollectionTest.java

...from Play.detectChanges() to a separate plugin.
the goal is to be able to override this behaviour: e.g. we don't want to restart play on every conf change - it slows down development process.
Ticket: https://play.lighthouseapp.com/projects/57987-play-framework/tickets/1990-extract-code-for-detecting-applicationconf-changes-from-playdetectchanges-to-a-separate-plugin

[#1990] extract code for detecting application.conf changes

---

framework/src/play/db/SQLSplitter.java
framework/test-src/play/db/SQLSplitterTest.java

"double semicolon" used to escape a semicolon and avoid splitting the same way Play 2.x supports escaping the single semicolon.
Useful to handle trigger or function declarations in evolutions scripts for SQL dialects that don't support dollar comments/delimiters (i.e. MySQL).
See [Lighthouse 2011](https://play.lighthouseapp.com/projects/57987-play-framework/tickets/2011-support-double-semicolon-escaping-in-evolution-scripts)

[#2011] "double semicolon" as escape in evolutions scripts

---

framework/src/play/PlayPlugin.java

It uses excessive memory and GC resources without need.
Use Collections.emptyList() and Collections.emptyMap() instead.
Lighthouse ticket: https://play.lighthouseapp.com/projects/57987-play-framework/tickets/2020-avoid-multiple-creation-of-new-arraysmaps

[#2020] avoid multiple creation of new arrays/maps

---

framework/dependencies.yml

groovy 2.4.6 has been released today.
It has quite a comprehensive changelog:
http://groovy-lang.org/changelogs/changelog-2.4.6.html
lighthouse ticket: https://play.lighthouseapp.com/projects/57987-play-framework/tickets/2029-upgrade-to-groovy-246

[#2029] upgrade to groovy-all 2.4.6

---

framework/templates/tags/i18n.tag
samples-and-tests/just-test-cases/app/controllers/tagDemos/TagDemos.java
samples-and-tests/just-test-cases/app/views/main.html
samples-and-tests/just-test-cases/app/views/tagDemos/TagDemos/i18n.html
samples-and-tests/just-test-cases/conf/messages

[lighthouse issue #2015](https://play.lighthouseapp.com/projects/57987/tickets/2015-i18n-tag-only-restore-the-first-character)

* [#2015] fix(i18n): Fix i18n tag only restore to restore all '%' characters

---

framework/src/play/db/jpa/Blob.java

Play's Blob Hibernate UserType isn't implementing all methods but throwing UnsupportedOperationExceptions for disassemble, assemble and replace. These methods are important if Hibernate's 2nd level cache is used.

[#2026] Blob: missing methods implemented to support (2nd level) caching

---

framework/src/play/Invoker.java
framework/src/play/PlayPlugin.java
framework/src/play/jobs/Job.java
framework/src/play/plugins/PluginCollection.java

In 1.3.1, Plugin filters do not behave the way documentation suggests they should.  (For example, see javadoc for PlayPlugin::Filter.)    
Everything works normally as long as only one filter is defined (typically the one for JPAPlugin), but as soon as a second enters the picture everything goes off the rails. In Job, only the filter belonging to the highest priority plugin is executed.  In Invoker, actions are executed once per filter.  This does not seem like the intended behavior.
This patch makes plugins stack in the way documentation suggests they should.

[#1947] [#1948] Fix PlayPlugin filter stacking.

---

framework/src/play/libs/WS.java
framework/src/play/libs/ws/WSAsync.java
framework/src/play/libs/ws/WSUrlFetch.java
framework/test-src/play/libs/TestHttpResponse.java
samples-and-tests/just-test-cases/test/WSTest.java

In http-client-async getResponseBodyAsStream cannot be called multiple times. This leads to WS.getStream to also must be called once.
Here is a proposal to not use getStream in getString method so getString can be called multiple times. This was the default behaviour in play 1.2.x. The modification leads to several regressions because ofter getString is used in logs before really using the response.
With this version getString use underlying getResponseBody that can be use multiple times.

[#2035] Fix regression in WS.getString between 1.2.x and 1.4.x

---

framework/src/play/cache/Cache.java
framework/test-src/play/cache/CacheTest.java

it's often called during Play! restart, when cache is not initialized yet
Lighthouse ticket: https://play.lighthouseapp.com/projects/57987-play-framework/tickets/2019-make-method-cacheclear-null-safe

[#2019] Make method Cache.clear() null-safe

---

framework/src/play/classloading/ApplicationClassloader.java

Use caches to speed up class  & assignable classes lookup: These methods are called quite often and for a large number of classes, it's desirable to avoid iterating over all of them every time. Using a profiler, there is a clear performance boost.

[#2018] class caches added

---

documentation/manual/configuration.textile
framework/src/play/mvc/Router.java

For SSL-enabled application that have early SSL-termination (meaning the application code sees it as a non-https request but with the `X-Forwarded-Proto` header set), using reverse routing out of the box can be somewhat of a pain, since it blindly uses the host request header (which is non-https) for the redirect url. This results in multiple redirects for applications that already have custom code to redirect non-secure requests in a `@Before` filter (as mine does). As a result, flash parameters are dropped due to the multiple redirection.
This PR adds a configuration setting that will force the Router's `reverse` method to use a secure url (https://) for the `actionDefinition`'s `host`.
This new configuration is of course **opt-in**, disabled by default. For what it's worth, I'm …

[#2036] Force secure reverse routes config

---

framework/src/play/libs/ws/WSAsync.java

by default `NettyResponse` uses `ISO 8859-1`, but we need `UTF-8` in most cases.
Ticket: [#2037](https://play.lighthouseapp.com/projects/57987-play-framework/tickets/2037-use-correct-encoding-in-method-wsasyncgetstring)

use correct encoding in method WSAsync.getString()

---

framework/src/play/data/validation/ValidationPlugin.java
framework/test-src/play/data/validation/ValidationTest.java

Validation.addError() with empty message variables failed, e.g. 
```java
Validation.addError("field", "message", "")
```
We fixed it.

support empty values in validation error arguments

---

framework/pym/play/application.py

Otherwise some tests fail sometimes, when variable `disable_random_jpda` is not defined in `self.play_env`. See stacktrace of failing test:
```python
[exec] ======================================================================
[exec] ERROR: testWithoutFlag (__main__.JvmVersionFlag)
[exec] ----------------------------------------------------------------------
[exec] Traceback (most recent call last):
[exec]   File "/home/jenkins/workspace/play/samples-and-tests/i-am-a-developer/mock.py", line 1201, in patched
[exec]     return func(*args, **keywargs)
[exec]   File "/home/jenkins/workspace/play/framework/../samples-and-tests/i-am-a-developer/test_jvm_version_flag.py", line 43, in testWithoutFlag
[exec]     play_app.java_cmd([])
[exec]   File …
```

fix KeyError: 'disable_random_jpda' in application.check_jpda

---

framework/src/play/data/binding/As.java
framework/src/play/data/binding/Binder.java
framework/src/play/data/binding/TypeBinder.java
framework/src/play/data/binding/types/CalendarBinder.java
framework/src/play/data/binding/types/DateBinder.java
framework/src/play/data/binding/types/DateTimeBinder.java
framework/test-src/play/data/binding/Data3.java
framework/test-src/play/data/binding/types/CalendarBinderTest.java
framework/test-src/play/data/binding/types/DateBinderTest.java

See ticket [2032](https://play.lighthouseapp.com/projects/57987/tickets/2032-do-not-swallow-exceptions-in-playdatabinding)

Dont swallow exceptions in binder

---

framework/src/play/templates/FastTags.java
framework/test-src/play/templates/FastTagsTest.java

This commit enhances the `#{form}` tag. It allows to specify the form action as a URL instead of a `ActionDefinition`. E.g. instead of `#{form @User.settings() ...` you could write `#{form '/user/settings' ...`. 
This is useful if you want to keep your URLs stable with a good `routes` file without wildcards and possibility to move your controllers/actions around without hunting through templates to find usages.
As a side effect - before adding the new feature, I added some tests for existing `#{form}` tag functionality. It had none up to this point.

Form tag url support pr

---

framework/src/play/vfs/VirtualFile.java

I think it is enough to check only once for `null` before calling the regex matcher.
This fix is needed if you really use "open file from errors pages" (a Play! developer feature):
```
#
```
Here is a nice summary how to use it with several os: [How open files in ide from debugger](https://pla.nette.org/en/how-open-files-in-ide-from-debugger)

[#2066] avoid NPE in regex matcher

---

framework/src/play/db/DBPlugin.java

The jndi: prefix was added at https://github.com/playframework/play1/pull/441.
But the `changed()` might not be detected when calling `onApplicationStart` in DBPlugin.java (it will return `false` if db.url and db.driver is not configured). And the datasource with `jndi:` prefix will not be initialized and not been added to DB.datasources.

Detect changed for JNDI datasource which using jndi: prefix

---

documentation/manual/configuration.textile

I think mentioning jndi: prefix in the documentation would be helpful for Glassfish users

Add documentation for jndi: prefix support

---

framework/src/play/classloading/enhancers/PropertiesEnhancer.java

add possibility to disable generating getters/setters 
(via setting `play.propertiesEnhancer.generateAccessors=false`)
it's useful because generation of getters/setters and replacing all field accesses with getters/setters is the slowest part of compilation process. Many applications do not really need it.

add possibility to disable generating getters/setters

---

framework/pym/play/commands/modulesrepo.py

https://play.lighthouseapp.com/projects/57987-play-framework/tickets/1919-building-modules-with-a-space-in-path-under-windows-fails

[#1919] fixes Building modules with a space in path under windows fails

---

framework/src/play/Play.java

otherwise the shutdown hook will keep the current `ApplicationClassloader` forever
Lighthouse ticket: https://play.lighthouseapp.com/projects/57987-play-framework/tickets/2072-play-has-memory-leaks

ticket #2072: set system classloader to shutdown hook

---

framework/src/play/mvc/results/Error.java
framework/src/play/mvc/results/NotModified.java
framework/src/play/mvc/results/Redirect.java
framework/src/play/mvc/results/RedirectToStatic.java
framework/src/play/mvc/results/RenderBinary.java
framework/src/play/mvc/results/RenderHtml.java
framework/src/play/mvc/results/RenderJson.java
framework/src/play/mvc/results/RenderTemplate.java
framework/src/play/mvc/results/RenderText.java
framework/src/play/mvc/results/RenderXml.java
framework/src/play/mvc/results/Status.java
framework/src/play/mvc/results/Unauthorized.java

We want to add public getters to all `Result` subclasses (first of all, `RenderTemplate`).
So we can catch them in unit-tests and verify all parameters

Add getters to Result classes

---

framework/src/play/templates/GroovyTemplate.java

Binding can only contain variables (basically, a Map), not properties.
If groovy doesn't find a variable, it throws a MissingPropertyException populating the stacktrace.
GroovyTemplate.getProperty() first calls the getVariable(), if it throws (happens very often if you have optional bindings), then it catches and delegates to getProperty(), that does some slow work itself again.
This small change avoids these excessive exceptions with stacktraces on every missing variable access.

avoid thousands of MissingPropertyExceptions

---

framework/src/play/data/binding/Binder.java
framework/test-src/play/data/binding/BinderTest.java

... to avoid holding custom binders in static list forever, holding reference to the initial ApplicationClassloader

ticket #2072: add method Binder.unregister()

---

framework/src/play/mvc/results/RenderJson.java

Instance of class Gson can be reused. This object is thread-safe.
So, instead of creating new Gson() every time, we can create it once and reuse.
PR for https://github.com/playframework/play1/issues/1058

#1058 Improve performance of RenderJson

---

documentation/commands/cmd-dependencies.txt
framework/pym/play/commands/deps.py
framework/src/play/deps/DependenciesManager.java

[#983] feat(DependenciesManager): add new option "nosync"
for issue #993

[#983] feat(DependenciesManager): sync option should be ON by default.

---

framework/src/play/classloading/ApplicationClassloader.java

remove method ApplicationClassloader.toString()
it can cause performance issues: some libraries (e.g. xalan) log ClassLoader.toString() many times

[#1090] Fix performance issue in classloader

---

framework/build.xml
framework/src/play/mvc/ActionInvoker.java
framework/src/play/mvc/Controller.java
framework/src/play/mvc/Http.java
framework/src/play/mvc/PlayController.java
samples-and-tests/nonstatic-app/app/controllers/Application.java
samples-and-tests/nonstatic-app/app/views/Application/index.html
samples-and-tests/nonstatic-app/app/views/main.html
samples-and-tests/nonstatic-app/conf/application.conf
samples-and-tests/nonstatic-app/conf/dependencies.yml
samples-and-tests/nonstatic-app/conf/messages
samples-and-tests/nonstatic-app/conf/routes
samples-and-tests/nonstatic-app/test/ApplicationTest.java

it would allow users to use custom implementations of base controller
See https://github.com/playframework/play1/issues/1095

Fixes #1095 add marker interface for play controllers

---

framework/src/play/server/Server.java

Many crashes during start in PROD mode are not logged anywhere and are difficult to analyze.
For example this will log invalid cron exceptions properly when running in PROD mode.

Catch top-level exceptions and log them properly

---

documentation/manual/configuration.textile
framework/src/play/data/parsing/ApacheMultipartParser.java

…file in a request.
The configuration parameters are: 'upload.sizeMax' and 'upload.fileSizeMax'.
The defaults stay the same -1 which means 'unlimited'.

[#1112] Allow to limit the size of whole request or the size of one uploaded file in a request

---

framework/src/play/Play.java
framework/src/play/libs/Files.java
framework/src/play/utils/OS.java
framework/src/play/utils/Utils.java
framework/test-src/play/libs/FilesTest.java

[Lighthouse #2079](https://play.lighthouseapp.com/projects/57987-play-framework/tickets/2079)

[#2079] fix(Files): Change the method to compare if two file refers to the same one

---

framework/src/play/Play.java
framework/src/play/plugins/PluginCollection.java
framework/test-src/play/plugins/ConfigurablePluginDisablingPluginTest.java
framework/test-src/play/plugins/PluginCollectionTest.java

make getPluginInstance() return the plugin of specific type

Avoid casting when calling getPluginInstance()

---

framework/src/play/db/jpa/JPABase.java
samples-and-tests/just-test-cases/app/models/ArrayIdEntity.java
samples-and-tests/just-test-cases/test/SimpleJPATest.java

The pull request moves _key() and adds unit tests for JPABase.equals() to give confidence that there were no behavioral changes.

[#2121] Move _key() after reference/null checks in JPABase.equals()

---

framework/src/play/classloading/ApplicationClassloader.java

currently Play 1.5 cannot find any Entity classes in precompiled mode

finds classes in precompiled folder too

---

framework/src/play/classloading/ApplicationClassloader.java
framework/src/play/db/jpa/JPAPlugin.java
framework/src/play/db/jpa/PersistenceUnitInfoImpl.java

revert ApplicationClassloader changes from #1114
fixing the real entity class loading problem

fix loaded entity classes in hibernate from #1114

---

documentation/manual/configuration.textile
framework/src/play/plugins/PluginCollection.java
framework/test-src/play/plugins/PluginCollectionTest.java
framework/test-src/play/plugins/custom-play.plugins.duplicate

Make it possible to load plugins from single `play.plugins` file

---

framework/src/play/mvc/CookieSessionStore.java
framework/src/play/mvc/Scope.java
framework/src/play/mvc/SessionStore.java

There are some problems with the default cookie-based sessions, including:
* It is very easy to overwrite changed session in concurrent AJAX request with unpredictable result
* Session replay attacks are possible by sending previous version of the session until it expires
This PR makes it possible to implement other backends for session storage, e.g. cache or database.
This is similar to CacheImpl, where new caching implementaions can be created.
The default implementation is CookieSessionStore that extracted as-is from Scope.Session class. All Scope.Session API is left 100% unchanged, so no breaking changes.
No new implementations are provided as of now, but we can create a separate PR with cache-based implementation.

Make it possible to change session store implementation

---

framework/src/play/mvc/results/Forbidden.java

the default error message will be "Access denied"
It's used in Controller.forbidden(), so de-facto it's the default value in most cases

create a default constructor for `play.mvc.results.Forbidden`

---

framework/src/play/inject/Injectable.java
framework/src/play/inject/Injector.java
framework/src/play/inject/RequireInjection.java

Hi,the Injector inject beans in controllers,now I enhance the function of the injector
[#Lighthouse 2138](https://play.lighthouseapp.com/projects/57987-play-framework/tickets/2138)

[#2138]enhance the function for the injector (Add the injectable interface)

---

framework/src/play/classloading/ApplicationClassloader.java

[#1823] Fix play.exceptions.CompilationException (fix for the fix #786)

---

framework/src/play/Logger.java
framework/src/play/Play.java
framework/src/play/server/Server.java

1228 fix spellling mistake

---

framework/src/play/mvc/Router.java

Switch from HTTPS to WSS (like we already do it for HTTP to WS) to support secure websocket connections. At least Chrome doesn't allow "mixed content" like using WS for HTTPS pages.

#1237 Use secure websocket protocol for secure pages

---

framework/src/play/mvc/WebSocketController.java

WebSocketController has to implement the "new" marker interface PlayController to keep it usable and working.

PlayController implemented

---

framework/pym/play/commands/daemon.py

rebase #839 on master
lighthouse: [#1896]
duplicates: lighthouse [#1910]
and fixes: lighthouse [#1860]

[#1896] fix play daemon stacktrace on [re]start-stop

---

framework/src/play/mvc/Controller.java
framework/test-src/play/mvc/ControllerTest.java

This solves the "await/Continuations error" when trying to run tests in if you're using jdk9+

fix(tests): issue #1200, added testing compatibility for jdk9+

---

framework/src/play/test/FunctionalTest.java
samples-and-tests/just-test-cases/app/controllers/Binary.java
samples-and-tests/just-test-cases/test/BinaryTest.java
samples-and-tests/just-test-cases/test/FunctionalTestTest.java
samples-and-tests/just-test-cases/test/TransactionalJPATest.java

P.S. it implements my comments for PR https://github.com/playframework/play1/pull/1246
* [#1849]  improve design of BinaryTest
P.S. it implements my comments for PR https://github.com/playframework/play1/pull/1246
* [#1849]  add method assertIsStaticFile() and special case allowing to test RenderStatic in functional tests
P.S. it implements my comments for PR https://github.com/playframework/play1/pull/1246
cf #1849, #1246, #1248

[#1849] restore checks in TransactionalJPATest that were accidentally deleted in PR 1246

---

framework/src/play/libs/WS.java
framework/src/play/libs/XML.java
framework/test-src/play/libs/TestXMLHttpResponse.java
framework/test-src/play/libs/XMLTest.java

Add method overloads that let you generate documents that you can naviagate with XPath while taking XML namespaces into account.
This adds method to get namespace-aware XML documents from strings, files, input streams and request bodies.
Without this, navigating the documents with XPath always returns null if namespaces are taken into account. I’ve added a few tests to demonstrate the issue.

Add support for navigating XML with namespaces.

---

framework/src/play/data/parsing/UrlEncodedParser.java
framework/test-src/play/data/parsing/UrlEncodedParserTest.java

This PR fixes the decoding of a query string from requests with content-type "application/x-www-form-urlencoded". Error detected in org.apache.common.codec.net.URLCodec so it is replaced by java.net.URLDecoder.

[#1212] Fix non-Latin characters decode in UrlEncodedParser

---

framework/src/play/data/binding/Binder.java
framework/test-src/play/data/binding/BinderTest.java

There seems to be most basic types in the Binder but
BigInteger was missing, even though BigDecimal was present.
Without the BigInteger binding fixtures for models using this type
will not load.
Fixes #1268

Add BigInteger binding

---

framework/build.xml
framework/src/play/templates/GroovyTemplateCompiler.java
samples-and-tests/fast-tag/app/controllers/Application.java
samples-and-tests/fast-tag/app/tags/OverridenFastTag.java
samples-and-tests/fast-tag/app/views/Application/index.html
samples-and-tests/fast-tag/conf/application.conf
samples-and-tests/fast-tag/conf/dependencies.yml
samples-and-tests/fast-tag/conf/messages
samples-and-tests/fast-tag/conf/routes
samples-and-tests/fast-tag/test/OverridenFastTagTest.java

https://github.com/playframework/play1/issues/1262

Allow to override default fast tags with empty namespace

---

documentation/manual/configuration.textile
framework/src/play/db/hikaricp/HikariDataSourceFactory.java

Hikari supports setConnectionInitSql() to register custom SQL to initialize a new connection. This is handy to configure the character set for the connection (e.g. "SET NAMES utf8mb4" in MySQL to make emojis etc. work ;)
I added a play config option to setup this property.

HikariCP: config property for init connection sql added

---

framework/src/play/db/DBPlugin.java

Fixes #1294 
Removes unneeded default MySQL character encoding and collation properties
Latest Connector/J documentation recommends no character encoding and collation properties to be set by default so that these values to be set by the server while not precluding these properties from being overriden by the client if necessary

Remove MySQL connection charset property defaults

---

documentation/manual/configuration.textile
framework/src/play/server/PlayHandler.java
framework/src/play/server/ServletWrapper.java

Fixes #1300 
The purpose of this PR is to allow user to define allowed methods that can be defined in 'X-HTTP-Method-Override'

[#1300] feat: Define allowed methods used in 'X-HTTP-Method-Override'

---

framework/pym/play/commands/help.py
play

https://play.lighthouseapp.com/projects/57987-play-framework/tickets/2128-feature-help-for-module-comannds-like-for-core-commands

[#2128] feature: help for module commands

---

framework/src/play/deps/DependenciesManager.java

This commit adds a non-zero exit code to the "play deps" command, allowing scripts to check if the dependencies were properly fetch or not.
We needed to be able to check how the dependencies fetching went for our integration process

Adds exit codes to play deps command

---

documentation/manual/tags.textile
documentation/manual_ja/tags.textile
framework/templates/tags/stylesheet.tag

The documentation of stylesheet.tag refers to default leading path
`/public/stylesheets`
instead of
`/public/stylesheets/`
The documentation also lacks the path attribute (which should be set to a path with a trailing slash).

[#1312] stylesheet.tag missing trailing slash in documentation

---

framework/src/play/data/binding/Binder.java
framework/src/play/data/binding/types/LocalDateBinder.java
framework/src/play/data/binding/types/LocalTimeBinder.java
framework/src/play/data/validation/InFutureCheck.java
framework/test-src/play/data/binding/types/LocalDateBinderTest.java
framework/test-src/play/data/binding/types/LocalTimeBinderTest.java

* Add LocalDate and LocalTime Binder
* Add LocalDate and LocalDateTime InFutureCheck
* Java 8 Date/Time Binder Support
N/A
N/A

* Java8 Date/Time Binder Support

---

framework/src/play/inject/Injector.java

otherwise `Class.forName` uses Injector's classloader which doesn't contain user provided classes.
Fixes https://github.com/playframework/play1/issues/1297

#1297 load session store using Play.classloader

---

framework/src/play/server/Server.java

This change avoids creating `ServerBootstrap` objects which are never bound to a port (for example, not creating the HTTPS server if the application doesn't have a `https.port` configured).  
The change is simple, it only moves the code which instantiates these objects into the following if statement.  Netty creates 2*(number of processor) "New I/O worker" threads when a `NioServerSocketChannelFactory` object is created, so this change avoids creating lots of threads that the application never uses.
For example, on a machine with 16 CPUs, this eliminates the creation of 32 threads that would otherwise exist for the lifetime of the Play server and never execute.  The benefit for eliminating these threads:
- Less thread pollution when viewing a Play! JVM with tools like jstack or visualvm. …

[#1935] Don't create CPU*2 "New I/O worker" threads for unused ports

---

documentation/manual/install.textile

Links to download and install Play in https://www.playframework.com/documentation/1.5.x/install are broken. The suggested links may point to different content but at least show a list of artifacts. :-)

Fix broken downloads link

---

framework/src/play/Logger.java
framework/src/play/classloading/ApplicationClasses.java
framework/src/play/classloading/ApplicationClassloader.java
framework/src/play/classloading/ApplicationCompiler.java
framework/src/play/classloading/BytecodeCache.java
framework/src/play/classloading/enhancers/Enhancer.java
framework/src/play/data/parsing/ApacheMultipartParser.java
framework/src/play/i18n/Lang.java
framework/src/play/libs/Codec.java
framework/src/play/libs/Crypto.java
framework/src/play/mvc/Controller.java
framework/src/play/mvc/Mailer.java
framework/src/play/templates/GroovyTemplate.java
framework/src/play/templates/TemplateLoader.java
framework/src/play/utils/OrderSafeProperties.java

Using more appropriate methods for replace single char and charsets constants.

Cleanup code

---

documentation/manual/configuration.textile
documentation/manual/evolutions.textile
framework/src/play/db/Evolutions.java
framework/test-src/play/db/ConfigurationTest.java

Fixes #1383 
Add support for a new configuration parameter to allow disabling database evolutions per database.
#1383

[#1383] 🆕 Ability to disable database evolutions on a datasource basis

---

documentation/manual/configuration.textile
framework/pym/play/application.py

* ♻ Adapt startup scripts to take into account new parameter
* 📝 Update documentation for the new parameter jpda.address
Fixes #1331
Add new configuration parameter jpda.address to allow to specify the listening address, useful for JDK >=9 to allow listening to other interface than localhost. For JDK < 9, this allows to restrict the service to localhost.

[#1331] 🆕 Add new parameter jpda.address support

---

documentation/manual/configuration.textile
documentation/manual/install.textile
framework/build.xml
framework/src/play/classloading/ApplicationCompiler.java
resources/application-skel/conf/application.conf
resources/idea/imlTemplate.xml
resources/idea/iprTemplate.xml
resources/module-skel/build.xml

Since https://github.com/playframework/play1/commit/6dabc5308399226cc7cb11d64fc12ebbd5529e8c play! is compiled and tested on jdk 11 and 17 in CI. So in my opinion it's good cause to migrate to jdk 11 in the next release.

make default jdk 11

---

.github/workflows/build-test.yml
framework/build.xml
framework/pym/play/commands/intellij.py
framework/test-src/play/templates/FastTagsTest.java

#1371
#1366
#1292
added ability to run IDEA with WSL
fixed test on Windows play.templates.FastTagsTest
now you can run IDEA from WSL
fixes the test that screams
end of line problem in jdk 11 and 17 under Windows and system variable "line.separator"
`System.setProperty("line.separator","\n");`
I solved the problem by inserting line breaks as they are in the system and now it will not test depend on OS
I added "action "it to the tests performed on OS-Windows and  jdk17 so that this situation would not happen
added run

fixed 'play idea' now is correctly for WSL Run GitHub Action on win and fixed test for Windows 

---

documentation/manual/jpa.textile
framework/src/play/db/jpa/JPQL.java
framework/test-src/play/db/jpa/JPQLTest.java

Fixes #xxxx
What does this PR do?
Why did you take this approach?
Are there any relevant issues / PRs / mailing lists discussions?

[#1278, #1343]  OrderBy support in simplified JPA queries for 1.5.x

---

documentation/manual/jpa.textile
framework/src/play/db/jpa/JPQL.java
framework/test-src/play/db/jpa/JPQLTest.java

This pull request:
* fixes an `old_master` -> `master` port of an old, unrelated pull request (#504) where some parts of "OrderBy" change sneaked in
* ports those `[#878] Add OrderBy support in simplified queries` commits which were never ported to new `master`
I voted for creating a preparing commit to make the cherry picking as seamless as possible.
I added `(cherry picked from commit xxxxxx)` the cherry picked commits to make it clear this is an `old_master` -> `master` port
I could add a whitespace fixup commit, as the original commits used TABs for indentation.
All details are in the original issue: #1278

GitHub issue #1278: OrderBy support in simplified JPA queries for 1.5.x

---

framework/src/play/cache/MemcachedImpl.java

`MemcachedImpl` forces the usage of `net.spy.memcached.compat.log.Log4JLogger` while it shouldn't.
Fixes https://github.com/playframework/play1/issues/1414.

Do not overwrite system property net.spy.log.LoggerImpl -> 1.7.1

---

framework/src/play/classloading/ApplicationClassloader.java
framework/src/play/data/binding/Binder.java
framework/src/play/db/jpa/JPAPlugin.java
framework/src/play/db/jpa/PersistenceUnitInfoImpl.java
framework/src/play/jobs/JobsPlugin.java
framework/src/play/libs/F.java
framework/src/play/plugins/PluginCollection.java
framework/src/play/server/HttpServerPipelineFactory.java
framework/src/play/templates/BaseTemplate.java
framework/src/play/templates/GroovyTemplate.java
framework/src/play/templates/GroovyTemplateCompiler.java
framework/src/play/templates/JavaExtensions.java
framework/src/play/test/Fixtures.java
framework/src/play/utils/Java.java

Fix warnings with generics

---

framework/src/play/db/jpa/HibernateInterceptor.java

When [Hibernate Envers](https://hibernate.org/orm/envers/) is triggered via an `@Audited` annotation, it attempts to insert a record in a related `AUD` table.
However, Play! assumes all related entities extend `JPABase`, which the `AUD` tables don't. This leads to a `ClassCastException` because `HashMap` is cast to `JPABase`.
By adding a check for `JPABase` here, we can avoid this problem. This effectively also checks for 'not null' which the previous implementation did.

Better compatibility with Hibernate Envers

---

framework/pym/play/commands/modulesrepo.py

* Play1 (1.7.1-35-g557a968a)
* Python 3.7.16
```
./play install cas 3.0
~ Will install cas-3.1
~ This module is compatible with: 1.1.x, 1.2.x
~ Do you want to install this version (y/n)? y
~ Installing module cas-3.1...
~
~ Fetching https://www.playframework.com/modules/cas-3.1.zip
Traceback (most recent call last):
File "./pp/play", line 168, in <module>
status = cmdloader.commands[play_command].execute(command=play_command, app=play_app, args=remaining_args, env=play_env, cmdloader=cmdloader)
File "/Users/tle/Work/clui/pp/framework/pym/play/commands/modulesrepo.py", line 67, in execute
install(app, args, env)
File "/Users/tle/Work/clui/pp/framework/pym/play/commands/modulesrepo.py", line 476, in install
Downloader().retrieve(fetch, archive)
File …
```

Fix missing HTTPMessage.getHeader()

---

framework/src/play/deps/YamlParser.java

A malicious web application's file crafted from a client could cause a remote code execution attack on a Linux or Windows server running PlayFramework.
Regarding new Yaml(), use a correct way to avoid deserialization vulnerabilities

feat(YamlParser): add SafeConstructor to enforce security

---

framework/pym/play/commands/modulesrepo.py

One solution to this issue: [Python AttributeError: module 'time' has no attribute 'clock'](https://github.com/playframework/play1/issues/1466)
`play install` command works after the changes made
```
#19 [stage-1  9/10] RUN play install deadbolt <<< 'y'
#19 1.347 ~        _            _ 
#19 1.347 ~  _ __ | | __ _ _  _| |
#19 1.347 ~ | '_ \| |/ _' | || |_|
#19 1.347 ~ |  __/|_|\____|\__ (_)
#19 1.347 ~ |_|            |__/   
#19 1.347 ~
#19 1.347 ~ play! 1.7.x-8070e1e3, https://www.playframework.com
#19 1.347 ~
#19 1.347 ~ Will install deadbolt-1.5.4
#19 1.347 ~ This module is compatible with: *
#19 1.347 ~ Do you want to install this version (y/n)? ~ Installing module deadbolt-1.5.4...
#19 2.184 ~
#19 2.184 ~ Fetching https://www.playframework.com/modules/deadbolt-1.5.4.zip
~ …
```

#1466 The clock function was removed from time module in Python 3.8

---

framework/pym/play/commands/modulesrepo.py

This fixes an error when "play build-module" is run on Python 3.7.11
load() missing 1 required positional argument: 'Loader'
This follows the recommendation shown on
https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
A loader argument is now required.  This commit assumes that dependencies.yml uses standard YAML tags, and so uses safe_loader. This is the most secure loader.
Fixes #1456
This pull request fixes a bug where "play build-module" throws an error with Python 3.7.11
```
Traceback (most recent call last):
File "/devel/dcostanz/github/play1_david_costanzo/play", line 168, in <module>
status = cmdloader.commands[play_command].execute(command=play_command, app=play_app, args=remaining_args, env=play_env, cmdloader=cmdloader)
File …
```

Fix "play build-module" by replacing yaml.load with yaml.safe_load

---

framework/src/play/utils/PThreadFactory.java
framework/src/play/vfs/VirtualFile.java

Fixes  #1527
Fix warning
```
AccessControlException in java.security has been deprecated and marked for removal
[javac]         } catch (AccessControlException e) {
[javac]                  ^
[javac] /home/runner/work/play1/play1/framework/src/play/utils/PThreadFactory.java:13: warning: [removal] SecurityManager in java.lang has been deprecated and marked for removal
```

chore(securitymanager): remove deprecated Security manager (#1527)
